language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
script: yarn test
branches:
  only:
    - '/.*/'

before_deploy: yarn buildstorybook
deploy:
  - provider: surge
    project: ./build/
    skip_cleanup: true
    domain: gumdrops-develop.surge.sh  
    on:
      repo: gumgum/gumdrops
      branch: feature/surge
  - provider: surge
    project: ./build/
    skip_cleanup: true
    domain: gumdrops.surge.sh  
    on:
      repo: gumgum/gumdrops
      branch: master